### ISSUE TITLE
How do I generate train *_eval.gt and *_eval.terms from *_raw_en.taxo

### ISSUE THREAD

**Issue by sahilmishra0012** [songjiang0909/BoxTaxo#1]

**Comment by songjiang0909** [comment]
Hello @sahilmishra0012 

The data is a preprocessed version from this [repo](https://github.com/yueyu1030/STEAM).  Hope it helps!

**Comment by sahilmishra0012** [comment]
What do .gt and .terms files represent?

**Comment by songjiang0909** [comment]
.terms are the entities, while .gt (groundtruth) are their parent entities in the taxonomy
